services:
  userservice:
    image: userservice
    container_name: user.api
    build:
      context: .
      dockerfile: services/user/User.Api/Dockerfile
    ports:
      - "5002:8080"
      - "5003:8081"

  gateway:
    image: gateway
    container_name: gateway.api
    build:
      context: .
      dockerfile: gateway/Gateway/Dockerfile
    ports:
      - "5004:8080"
      - "5005:8081"
        
  user.database:
    image: postgres:latest
    container_name: user.database
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/user-db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  chat.api:
    image: chat.application
    container_name: chat.api
    build:
      context: .
      dockerfile: services/chat/Chat.Application/Dockerfile
    ports:
      - "7002:8080"
      - "7003:8081"
