@Gateway_HostAddress = http://localhost:5004
@AccessToken = CfDJ8I7JDFhk8_9OskCPwbwVLDrEV1FTpHVedQmJ3jGicCSvTrM9w3cidSKTKOop4ePQmcEmY6OvWIKput_Meb1K1yJGxGBUltZzgS_vyB8rSO1AzrrU_0AqNRTR16Mf_Qgn5a7v1U0RQQSC86DRpLMq2ipI-twjtKAXBQd2yhCLcOjuBb5zWSJCQ6b6lkTJhVCW5juP6XdPaXS11mbVH3Ltmrj7guBQnGbEG5HEt2z_l3qGP_6ugD04e5d-8XdRGdJhdpBxdUntNOD50FalhrXSlFMFWyHhuG5ZjoTtbaWD-klqgbwicw3Zdx87Om9nlK30ZYQ0oE5280VDvav4lASYFAlUWkgeFto59yqR9stfPUzoXvIL1WafXdrASLtklUBKpwTJzTWVy_-0BLB4gaQmDSA

GET {{Gateway_HostAddress}}/login/
Accept: application/json

###

GET {{Gateway_HostAddress}}/api/weatherforecast/
Authorization: Bearer {{AccessToken}}
###
